FROM composer:1 AS composer

FROM php:7.3-cli

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN apt update \
    && apt install --no-install-recommends -y git unzip

WORKDIR /app
COPY composer.json .

RUN composer update --prefer-dist --prefer-lowest --prefer-stable

RUN vendor/bin/simple-phpunit install

COPY . .

ENV SYMFONY_DEPRECATIONS_HELPER=weak
RUN vendor/bin/simple-phpunit -v
