name: Static

on:
    push:
        branches:
            - master
    pull_request:
    release:

jobs:
    composer-validate:
        name: Validate composer.json
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Validate
                run: composer validate --strict
